#!/bin/bash
#####################################################################
#	Program :														#
#			Extract the a series of structures and then write the 	#
#			g09 input file											#
#	Input :															#
#			$1 = test.txt ; store a series of structure				#
#			$2 = header.txt ; info. of $rem							#
#           $3 = ecp                                                #
#	Output :														#
#			lots of *.com											#
#                                                                   #
#   History:                                                        #
# 2016/04/20, Grace, 1st. ver.                                      #
# 2019/03/26, Grace, bugs from the negative coordinate              #
# 2020/09/18. Grace, add the third input file as the footer.        #
#####################################################################

# Step 1 Check the input arguments
[ "$1" == "" ] && echo "file $1 is not exist, exit" && exit
[ "$2" == "" ] && echo "file $1 is not exist, exit" && exit

natom=$(head -n 1 $1)
natom_2=$(($natom+2))
fileLine=$(wc -l $1 | awk '{print $1}')
nfile=$(( $fileLine/($natom+2) ))

read -p 'Please key-in the charge: ' charge
read -p 'Please key-in the multiplicity: ' multi

for (( i=1;i<=$nfile;i++))
do
	head -n $(( $natom_2*$i )) $1 | tail -n $natom_2 > tmp.txt
	name=$(sed -n '2,2 p' tmp.txt)
    
	if [ `echo $name | grep -c \-` = 1 ]
	then
		name=n$name
	fi
	
    name=$(echo $name | sed 's/ //g')

cat << EOF > "${name}".com 
`cat $2` 

scan potential 

$charge $multi
`tail -n $natom tmp.txt`

EOF

# if [ -f $3 ] 
# then 
#     cat $3 >> "$name".com 
# fi

done

rm -f tmp.txt
