#!/bin/bash
#################################################################################
# Program :                                                                     #
#   Create SLURM file(s) to submit electronic structure input file(s).          # 
#   Programs: ORCA 6.1, GAUSSIAN16, Jellyfish, (Q-Chem 5.3, Molpro 2019).       #
#                                                                               #
# History:                                                                      #
# 2015-2020, Grace, SGE versions.                                               #
# 2026/04/10, Grace, Migrated to SLURM for HPC (Hannover).                      #
#################################################################################

# Main program
function main(){
    # 0. global variables setting 
        USAGE='Usage: qesub [ -e orca|g16|jellyfish|qchem|molpro ] [ -np procs ] infile'

        debug=''
        threads=1
        partition='mpp.share' # Standard LUIS partition
        time='24:00:00'        # Default time limit
        tag=''
        prcs=1                # DEFAULT PROCESSORS (Allows 'qesub he.inp' to work)

    # 1. check arguments
        checkArg $@ 
    
    # 2. check and count input files
        genlist $checkArg $input 
    
    # 3. user defined: select amount of nodes/batches
        getNnode list.dat 

    # 4. generate SLURM batch scripts
        genSLURMfile $getNnode list.dat 

    # 5. submit jobs
        for name in `cat SLURMlist.dat`
        do 
            sbatch $name 
        done 
        rm -f SLURMlist.dat 
}

function checkArg()
{
    until [ $# -eq 0 ]
    do 
        case $1 in 
        '-e')
            est=$2
            shift 2
        ;;
        '-np') 
            prcs=$2
            shift 2
        ;;
        '-p') 
            partition=$2
            shift 2
        ;;
        '-t')
            time=$2
            shift 2
        ;;
        '-h'|'--help') 
            showIllustration
        ;;
        *)
            input=$1
            check_file_extension $input

            case $input in 
            'all') checkArg='2' ;;
            'fail') checkArg='3' ;;
            *.dat) checkArg='4' ;;
            *) checkArg='1' ;;
            esac
            shift
        ;;
        esac
    done  

    if [ "$input" == '' ]; then showIllustration; fi
}

function check_file_extension()
{

    ext="${1##*.}"

    if [ -z "$est" ]; then
        if [ "$ext" == "com" ]; then
            est='g16'
        elif [ "$ext" == "jlf" ]; then
            est='jellyfish'
        else
            est='orca'
        fi
    fi

    if [ "$est" == "g16" ]; then
        inp_ext='com'; out_ext='log'
    elif [ "$est" == "jellyfish" ]; then
        inp_ext='jlf'; out_ext='jlf'
    else
        inp_ext='inp'; out_ext='out'
    fi

}

function jellyfish_input()
{
    # $1=$job; job name 

    cat << JFEOF
export LD_LIBRARY_PATH=/bigwork/nhcahsch/envs/jellyfish/lib:\$LD_LIBRARY_PATH
export QT_QPA_PLATFORM=offscreen

cd /bigwork/nhcahsch/conda/Jellyfish/build

printf "load \${SLURM_SUBMIT_DIR}/${job}.jlf\ncalculate all -r\nsave \${SLURM_SUBMIT_DIR}/${job}_result\nexit\n" | ./JellyfishCMD/JellyfishCMD
JFEOF
}



function genlist()
{
    case "$1" in 
    '1') echo $2 | cut -d '.' -f 1 > list.dat ;;
    '2') ls *.$inp_ext | sed "s/\.$inp_ext//" > list.dat ;;
    '3') 
        ls *.$out_ext | sed "s/\.$out_ext//" > alljobs.dat 
        rm -f list.dat; touch list.dat 
        for name in `cat alljobs.dat`; do 
            case "$est" in
                'orca') num=$(grep -c 'ORCA TERMINATED NORMALLY' $name.$out_ext) ;;
                'qchem') num=$(grep -c 'Have a nice day' $name.$out_ext) ;;
                'g16') num=$(grep -c 'Normal termination' $name.$out_ext) ;;
            esac 
            [ "$num" -eq 0 ] && echo $name >> list.dat 
        done 
        rm -f alljobs.dat 
    ;;
    '4') cat $2 | sed "s/\.$inp_ext//" > list.dat ;;
    esac 
}

function getNnode()
{
    njobs=$(wc -l $1 | awk '{print $1}')
    if [ $njobs -eq 1 ]; then getNnode='1'
    else
        echo '--------------------------------------------------------'
        echo "Amount of jobs: $njobs"
        read -p 'How many batch files do you want to split into? ' getNnode
        echo '--------------------------------------------------------'
    fi
}

function genSLURMfile()
{
    nNode=$1
    njobs=$(wc -l $2 | awk '{print $1}')
    jobname=( `cat $2` )
    [ $checkArg -ne 4 ] && rm -f list.dat 

    quotient=$(( $njobs/$nNode ))
    remainder=$(( $njobs%$nNode ))
    sgelist=(WagakkiBand SuzuhanaYuko Machiya NinagawaBeni IbukuroKiyoshi Asa KaminagaDaisuke Wasabi Kurona)
    
    rm -f SLURMlist.dat 
    ini_job=0
    for ((Node_i=1;Node_i<=$nNode;Node_i++))
    do 
        sname=${sgelist[$(( $RANDOM%9 ))]}
        [ -f "$sname.sh" ] && sname="${sname}_$Node_i"
        
        SLURMheader $sname
        
        if [ "$remainder" -eq 0 ]; then joblen=$quotient
        else
            if [ "$Node_i" -le $remainder ]; then joblen=$(( $quotient + 1 ))
            else joblen=$quotient; fi 
        fi 
        
        part_jobname=${jobname[@]:$ini_job:$joblen}
        ini_job=$(( $ini_job + $joblen ))
        
        for job in $part_jobname; do
            case $est in
                'orca')   echo "\$(which orca) $job.inp > $job.out" >> $sname.sh ;;
                'g16')    echo "g16 < $job.com > $job.log" >> $sname.sh ;;
                'jellyfish') jellyfish_input $job >> $sname.sh ;;
                'qchem')  echo "qchem -nt $prcs $job.inp $job.out" >> $sname.sh ;;
                'molpro') echo "molpro < $job.inp > $job.out" >> $sname.sh ;;
            esac
        done
        echo $sname.sh >> SLURMlist.dat 
    done 
}

function SLURMheader()
{
cat << EOF > $1.sh
#!/bin/bash -l
#####################################################################
#  Program :                                                        #
#       Submit the EST job(s) through SLURM workload manager.       #
#####################################################################

#SBATCH --job-name=$1
#SBATCH --partition=$partition
#SBATCH --ntasks=$prcs
#SBATCH --nodes=1
#SBATCH --mem=8G
#SBATCH --time=$time
#SBATCH --output=$1_%j.log

module purge
EOF

case $est in
    'orca') 
        echo "module load GCC/13.2.0 OpenMPI/4.1.6 ORCA/6.1.0" >> $1.sh 
    ;;
    'g16')  
        echo "module load Gaussian/16.C.01" >> $1.sh 
        ;;
    'jellyfish') 
        echo "export LD_LIBRARY_PATH=/bigwork/nhcahsch/envs/jellyfish/lib:\$LD_LIBRARY_PATH" >> $1.sh 
        echo "export QT_QPA_PLATFORM=offscreen" >> $1.sh 
    ;;
esac

echo '' >> $1.sh 

cat << EOF >> $1.sh
cd \$SLURM_SUBMIT_DIR
echo 'Job starts'
echo "    Host: \$HOSTNAME"
echo '    Date:' \`date\`

EOF
}

function showIllustration()
{
    echo $USAGE
    read -r -s -p $'Press enter to view manual...\n' 
    /usr/bin/perl -x $0
    exit 
}

main $@

exit

# ====================== perl script start =========================
#!/usr/bin/perl 

use strict;
use Pod::Usage;
pod2usage(-exitstatus => 0, -verbose => 2);

__END__

=head1 NAME

qesub - submit job(s) relating to elctronic structure theory (EST) program to SLURM. 

=head1 SYNOPSIS

I<qesub> [ options ] I<infile> 

=head2 Infile:

Four modes are provided:

=over 5

=item 1. I<$infile> = B<filename>; submit single job

=item 2. I<$infile> = 'B<all>'; submit all jobs in the current folder

=item 3. I<$infile> = 'B<fail>'; submit failed jobs

=item 4. I<$infile> = B<*.dat>; submit selected jobs in a list

=back

=head2 Options:

=over 8

=back

=head3

=over 8

=item -h, --help    show this help message and exit

=back

=head3 B<EST related:>

=over 8

=item -e [B<orca|g16|jellyfish>]      assign EST program 

=back

=head3 B<SLURM related:>

=over 8

=item -np B<procs>  invoke a parallel job with B<procs> cpus.

=item -p B<partition>    specify the SLURM partition.

=item -t B<time>    specify the time limit for the job (format: HH:MM:SS).

=back

=head1 EXAMPLES

 Submit an ORCA job with 1 core (Minimum Syntax):
 ]$ qesub molecule.inp 

 Submit an ORCA job with 8 cores:
 ]$ qesub -np 8 molecule.inp 

 Submit all the jobs in the current directory: 
 ]$ qesub all 

=head1 AUTHOR

=over 8

=item 2026 - Hsiao-Han (Grace) Chuang <chuang@aci.uni-hannover.de>

=back 

=cut
